# Generated by Django 5.1.3 on 2024-12-03 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybudgetapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Customer',
        ),
    ]
