# Generated by Django 5.1.3 on 2024-12-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybudgetapp', '0003_customer_groups_customer_is_active_customer_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
