# Generated by Django 5.1.3 on 2024-12-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybudgetapp', '0004_alter_customer_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField()),
                ('account_name', models.CharField(max_length=50)),
                ('account_number', models.IntegerField()),
            ],
        ),
    ]
