# Generated by Django 5.1.3 on 2024-12-07 04:42

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybudgetapp', '0006_paymentschedule_alter_limits_account_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentschedule',
            options={'ordering': ['-scheduled_date', '-created_at'], 'verbose_name': 'Payment Schedule', 'verbose_name_plural': 'Payment Schedules'},
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='category',
            field=models.CharField(blank=True, help_text='Optional categorization of the payment', max_length=50, null=True, verbose_name='Payment Category'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Associated User'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='Amount must be greater than zero'), django.core.validators.MaxValueValidator(100000, message='Amount exceeds maximum limit')], verbose_name='Payment Amount'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Timestamp'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='description',
            field=models.TextField(blank=True, help_text='Optional detailed description of the payment', max_length=500, null=True, verbose_name='Payment Description'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='recurrence',
            field=models.CharField(choices=[('ONE_TIME', 'One-time'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BI_WEEKLY', 'Bi-Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('SEMI_ANNUALLY', 'Semi-Annually'), ('ANNUALLY', 'Annually')], default='ONE_TIME', max_length=20, verbose_name='Recurrence Pattern'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='scheduled_date',
            field=models.DateField(help_text='Date when the payment is scheduled to occur', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 12, 7), message='Scheduled date cannot be in the past')], verbose_name='Scheduled Date'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Update Timestamp'),
        ),
        migrations.AddConstraint(
            model_name='paymentschedule',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='positive_amount'),
        ),
    ]
