# Generated by Django 5.1.3 on 2024-12-09 19:06

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybudgetapp', '0007_alter_paymentschedule_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('account_type', models.CharField(choices=[('phone', 'Phone Number'), ('bank', 'Bank Account'), ('credit_card', 'Credit Card'), ('crypto', 'Crypto Wallet')], max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('credit_card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('wallet_address', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(max_length=256)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('cvc', models.IntegerField(blank=True, null=True)),
                ('account_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('customer', 'account_name')},
            },
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_expenditure', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Max Expenditure Limit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limit', to='mybudgetapp.account')),
            ],
        ),
        migrations.DeleteModel(
            name='Limits',
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='scheduled_date',
            field=models.DateField(help_text='Date when the payment is scheduled to occur', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 12, 9), message='Scheduled date cannot be in the past')], verbose_name='Scheduled Date'),
        ),
    ]
