# Generated by Django 5.1.3 on 2024-12-10 08:10

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybudgetapp', '0008_account_limit_delete_limits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='scheduled_date',
            field=models.DateField(help_text='Date when the payment is scheduled to occur', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 12, 10), message='Scheduled date cannot be in the past')], verbose_name='Scheduled Date'),
        ),
    ]
