# Generated by Django 5.1.3 on 2024-12-10 15:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybudgetapp', '0010_remove_account_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('additional_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('housing_expense', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('utilities_expense', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('groceries_expense', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('transportation_expense', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('entertainment_expense', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('savings_expense', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('emergency_fund_target', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('specific_goal_description', models.CharField(blank=True, max_length=255, null=True)),
                ('goal_progress_notes', models.TextField(blank=True, null=True)),
                ('net_surplus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('week_start_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly Budget',
                'verbose_name_plural': 'Weekly Budgets',
                'ordering': ['-created_at'],
            },
        ),
    ]
